### ISSUE TITLE
Bad heroku git URL

### ISSUE THREAD

**Issue by Inza** [drone-plugins/drone-heroku#3]
This plugin is using bad repository URL for pushing to Heroku.

from a Heroku app foo-app it creates

`git@git.heroku.com:foo-app.git` clone url

but it should be 

`git@heroku.com:foo-app.git`

without the `git.` subdomain

Do you plan to fix this? Or is there any way how to directly specify the push repository URL? Instead of app name?

Thanks

**Comment by Inza** [comment]
I have created a pull request to fix this #4

**Comment by tboerger** [comment]
Fixed with #4
